### PR TITLE
Improve handling of future dates

### PR DESCRIPTION
**Pull request by dkirkby**
Astropy uses IERS tables to model UT1-UTC offsets and polar motion in its time and coordinates modules.  This PR adds a function `utils.freeze_iers()`:
```
    This should be called at the beginning of a script that calls
    astropy time and coordinates functions which refer to the UT1-UTC
    and polar motions tabulated by IERS.  The purpose is to ensure
    identical results across systems and astropy releases, to avoid a
    potential network download, and to eliminate some astropy warnings.

    After this call, the loaded table will be returned by
    :func:`astropy.utils.iers.IERS_Auto.open()` and treated like a
    a normal IERS-B table by all astropy code.

    See `http://docs.astropy.org/en/stable/utils/iers.html`_ for details.

    This function returns immediately after the first time it is called,
    so it it safe to insert anywhere that consistent IERS models are
    required, and subsequent calls with different args will have no
    effect.

    The :func:`desisurvey.utils.plot_iers` function is useful for inspecting
    IERS tables and how they are extrapolated to DESI survey dates.

    Parameters
    ----------
    name : str
        Name of the file to load the frozen IERS table from. Should normally
        be relative and then refers to this package's data/ directory.
        Must end with the .ecsv extension.
    ignore_erfa_warnings : bool
        Ignore ERFA warnings about future dates generated by astropy time,
        coordinates functions.  Specifically, warnings containing the
        string "dubious year" are filtered out.
```

### CODE REVIEW

**Comment by dkirkby** [comment]
The new file `data/frozen_iers.ecsv` was generated with `utils.update_iers()` and gives the following extrapolation:
iers_frozen

This file will be periodically updated (e.g., with major releases) but will never model more than 1-year in the future.

**Comment by dkirkby** [comment]
One possible issue is that a new unit test involves downloading an IERS-A file.  Is this a problem or is there some way to mark this as needed a network for travis @sbailey @weaverba137?

**Comment by sbailey** [comment]
The current behavior seems ok -- without a network the test will fail but at least it tells you that it requires a network before it fails.  It might be somewhat nicer to add a network availability check as part of loading the test module, and then conditionally skip the test if the network isn't available at all.  Travis should have network availability when the test runs, otherwise the initial configuration of the environment will have had many problems.

I do still get  a lot of IERS warnings about future dates while running the tests.  I was hoping that the docstring phrase "and to eliminate some astropy warnings" meant that we would be using the frozen file and not getting these warnings by default.  e.g.
```
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
```

There is also another astropy 1.2 clobber vs. 1.3 overwrite error:
```
======================================================================
ERROR: test_update_iers (desisurvey.test.test_utils.TestUtils)
Test updating the IERS table.  Requires a network connection.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desisurvey/py/desisurvey/test/test_utils.py", line 44, in test_update_iers
    utils.update_iers(save_name)
  File "/Users/sbailey/desi/git/desisurvey/py/desisurvey/utils.py", line 159, in update_iers
    iers.write(save_name, format='ascii.ecsv', overwrite=True)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/table/table.py", line 2349, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/registry.py", line 403, in write
    writer(data, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 685, in write
    writer = get_writer(Writer=Writer, fast_writer=fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 615, in get_writer
    writer = core._get_writer(Writer, fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/core.py", line 1435, in _get_writer
    writer = Writer(**writer_kwargs)
TypeError: __init__() got an unexpected keyword argument 'overwrite'
```

**Comment by weaverba137** [comment]
I guess if IERS-A is a small file, I'd just leave the test as is.  If it's a big one, then I think we can look at some other DESI unit tests that already skip downloads.

**Comment by dkirkby** [comment]
I added some more warning filters for those IERS messages and handled the overwrite/clobber mess.  I also fixed an AstropyDeprecationWarning with 1.3 that hopefully doesn't break 1.2.  Could you please check the tests again @sbailey on your system?

**Comment by sbailey** [comment]
No luck on the clobber vs. overwrite mess:
```
======================================================================
ERROR: test_update_iers (desisurvey.test.test_utils.TestUtils)
Test updating the IERS table.  Requires a network connection.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desisurvey/py/desisurvey/utils.py", line 168, in update_iers
    iers.write(save_name, format='ascii.ecsv', overwrite=True)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/table/table.py", line 2349, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/registry.py", line 403, in write
    writer(data, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 685, in write
    writer = get_writer(Writer=Writer, fast_writer=fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 615, in get_writer
    writer = core._get_writer(Writer, fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/core.py", line 1435, in _get_writer
    writer = Writer(**writer_kwargs)
TypeError: __init__() got an unexpected keyword argument 'overwrite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desisurvey/py/desisurvey/test/test_utils.py", line 44, in test_update_iers
    utils.update_iers(save_name)
  File "/Users/sbailey/desi/git/desisurvey/py/desisurvey/utils.py", line 170, in update_iers
    iers.write(save_name, format='ascii.ecsv', clobber=True)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/table/table.py", line 2349, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/registry.py", line 403, in write
    writer(data, *args, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 685, in write
    writer = get_writer(Writer=Writer, fast_writer=fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 615, in get_writer
    writer = core._get_writer(Writer, fast_writer, **kwargs)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/site-packages/astropy/io/ascii/core.py", line 1435, in _get_writer
    writer = Writer(**writer_kwargs)
TypeError: __init__() got an unexpected keyword argument 'clobber'
```

**Comment by dkirkby** [comment]
Lets revisit the network downloading unit test if it actually becomes a problem.  One of the points of this PR is that production code never needs to do a network download, so this test is only exercising the maintenance code needed to periodically update our local IERS table.

**Pull request merged**
