### PR TITLE
Fix test suite

### PR DESCRIPTION
**Pull request by weaverba137**
This PR fixes the test suite so that `python setup.py test` works.  There are other problems with the unit tests.  @dkirkby, @sbailey, let's use the discussion of the PR to debug the remaining issues.

### CODE REVIEW

**Comment by weaverba137** [comment]
Here are the unit tests that still have problems:

* test_etc.py: problem caused not by desisurvey, but by speclite, which is using `basestring`.  This is not Python 3 compliant.
* test_nextfield.py:  Don't know what is causing this:
```
======================================================================
ERROR: test_nfs (desisurvey.test.test_nextfield.TestNextField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/test/test_nextfield.py", line 53, in test_nfs
    tileinfo['tileID'], t0 + i * u.min, 30 * u.s,
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
```
* test_progress.py:  Not sure why 10 is an invalid tile number.  You are testing against the test-0.7.0 branch of desimodel correct?
```
======================================================================
ERROR: test_ctor (desisurvey.test.test_progress.TestProgress)
Create a new table from scratch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/test/test_progress.py", line 40, in test_ctor
    self.assertEqual(type(p.get_tile(10)), astropy.table.Row)
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/progress.py", line 279, in get_tile
    raise ValueError('Invalid tile_id {0}.'.format(tile_id))
ValueError: Invalid tile_id 10.

----------------------------------------------------------------------
```
* test_surveyplan.py: `False` is not `True`.  Maybe the same as above, test against the test branch of desimodel?
```
======================================================================
FAIL: test_planning (desisurvey.test.test_surveyplan.TestSurveyPlan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/test/test_surveyplan.py", line 67, in test_planning
    self.assertTrue(np.any(np.in1d(plan0['TILEID'][10:], plan1['TILEID'])))
AssertionError: False is not true

----------------------------------------------------------------------
```
* test_utils.py: These tests work, but it looks like you're downloading the same file twice.
* Finally, consider making tests independent of the environment variable `DESISURVEY`, because in say, a Travis test, that variable might not be defined.  There are more Pythonic ways of doing that.

**Comment by dkirkby** [comment]
I made the additional fixes required when $DESISURVEY is not defined and tested (using "python setup.py test") under py27 and py35.  I think this is ready to merge, but it would be helpful if @sbailey can confirm since he has such a good track record of finding broken unit tests.

**Comment by weaverba137** [comment]
@dkirkby, please see my previous comment for some broken tests I already found.  I think some of them are caused by using the test branch of desimodel, which one would do during a Travis test, rather than the main/trunk version of desimodel.

**Comment by dkirkby** [comment]
I can't reproduce those errors using the master branches of all required pkgs in a clean py35 conda env.  Specifically, all tests pass running "python setup.py test" with:
```
  - desimodel==0.7.0.dev204
  - desisurvey==0.7.0.dev1
  - desiutil==1.9.5.dev507
  - ephem==3.7.6.0
  - fitsio==0.9.11
  - healpy==1.10.3
  - speclite==0.5
  - specsim==0.10.dev717
  - surveysim==0.6.0.dev1
```

**Comment by weaverba137** [comment]
@dkirkby, which version of the desimodel *svn* data are you using?

**Comment by weaverba137** [comment]
In the case of speclite, I am using the latest master, which still contains references to `basestring`, see https://github.com/dkirkby/speclite/blob/master/speclite/filters.py#L1303

**Comment by weaverba137** [comment]
Ah, right, I just found dkirkby/speclite#26, so I'll let the speclite errors pass.

**Comment by weaverba137** [comment]
What is the branch `fix_plan_tests`? Is that related?

**Pull request merged**
