### PR TITLE
support astropy 4.2; switch to github actions for testing

### LINKED ISSUE #133: revive tests with GitHub actions
Travis tests are gone, so pull requests currently aren't running any automated unit tests.  Convert to using GitHub actions; desiutil, desispec, and desitarget are all examples for using that within the DESI context.

@dkirkby or @schlafly could you take care of this?

### LINKED ISSUE #137: reading horizons_2020_week1_moon.csv broken under astropy 4.2
This code used in test_ephem.py and test_utils.py is broken under astropy 4.2 because the last column is no longer parsed as name "col10":
```
        # Configure a CSV reader for the Horizons output format.
        csv_reader = astropy.io.ascii.Csv()
        csv_reader.header.comment = r'[^ ]'
        csv_reader.data.start_line = 35
        csv_reader.data.end_line = 203
        # Read moon ephemerides for the first week of 2020.
        path = astropy.utils.data._find_pkg_data_path(
            os.path.join('data', 'horizons_2020_week1_moon.csv'),
            package='desisurvey')
        cls.table = csv_reader.read(path)
        # Horizons CSV file has a trailing comma on each line.
        cls.table.remove_column('col10')
```

I suggest moving this `horizons_2020_week1_moon.csv` reader into a single place that both test_ephem.py and test_utils.py can use, ensuring that it works with both astropy 4.0.x and 4.2.x, and switch from using `astropy.utils.data._find_pkg_data_path` to `pkg_resources.resource_filename` to avoid using a `_underscore_hidden` function from astropy that may break again in a future release.

### PR DESCRIPTION
**Pull request by sbailey**
This PR
  1. fixes #137 by fixing the parsing of horizons moon ephem under astropy 4.2
  2. fixes #133 by switching from travis to github actions for CI testing

I suspect that (2) will take me a few more iterations to get the config right, so apologies in advance for the spam while I test the tests.

### CODE REVIEW

**Comment by sbailey** [comment]
@weaverba137 could you setup a COVERALLS_REPO_TOKEN for desisurvey?  I'm not sure if we ever had coveralls configured for desisurvey, and/or what the procedure is to do that.  Thanks.

**Comment by weaverba137** [comment]
Done!

**Comment by sbailey** [comment]
Thanks @weaverba137 .

@dkirkby @schlafly I think this is a straightforward PR to replace travis tests with github actions, and to fix tests under astropy 4.2 .  It does not change any core code (only tests).  I'll leave this open for a bit if you have any comments or requests, but otherwise I plan to merge this by the end of today and make a new desisurvey tag.

**Comment by schlafly** [comment]
Let me just thank you for fixing this.  I don't see any issues.  Feel free to merge.

**Comment by dkirkby** [comment]
Yes, thanks @weaverba137!

**Pull request merged**
