### PR TITLE
Updates for survey margin estimates

### PR DESCRIPTION
**Pull request by dkirkby**
Work in progress...

### CODE REVIEW

**Comment by dkirkby** [comment]
Unit tests are failing now since they need an updated version of desimodel (git + svn).

**Comment by dkirkby** [comment]
This is ready to merge and tag now as 0.10.4.  This PR adds new functionality without breaking any backwards compatibility, and tests are passing.

The next tag 0.11.0 will introduce some major changes to simplify and speed up the scheduler logic and survey simulations.

Please review if you have time today @sbailey @weaverba137 @moustakas.  Otherwise, I will merge and tag tomorrow (Tue) morning.

**Comment by weaverba137** [comment]
Looks fine to me.

**Comment by sbailey** [comment]
Code changes look fine, though I haven't tried running it myself so I'm trusting that "adds new functionality without breaking any backwards compatibility" is correct (and I'll open a post-merge ticket if it isn't...).  Merge when ready.

**Pull request merged**
