### PR TITLE
First pass at config data

### PR DESCRIPTION
**Pull request by dkirkby**
Work in progress towards centralizing all package config data in a single YAML file.

Not ready to merge yet, but please review the proposed YAML file in `data/config.yaml`.

### CODE REVIEW

**Comment by dkirkby** [comment]
I am going to start converting the `ephemerides` module to use the new config scheme now.

**Comment by dkirkby** [comment]
Conversion of the `ephemerides` module is finished and, after some tweaks, I am happy with the config API.

**Comment by sbailey** [comment]
config.yaml structure looks ok, though we may want to track the full depth region as a separate list of tiles in that field rather than a rectangle + first pass padding.

max_airmass: For the science requirements document, we decided to specify this as max zenith angle (60 deg) instead to avoid ambiguities from which airmass formula is used.

`timezone: US/mountain` does that imply daylight savings, i.e. is `US/mountain` shorthand for MST vs. MDT depending up time of year?  Could/Should we specify this as UTC-7 instead?

Side note: github renders this file without indentation, but the file itself does have indentation.  Odd.

**Comment by weaverba137** [comment]
I believe `US/Arizona` is what you want.

**Comment by dkirkby** [comment]
> we decided to specify this as max zenith angle (60 deg) instead

I would like to avoid mixing zenith and altitude angles, so how about `min_altitude: 30 deg`?

> I believe US/Arizona is what you want.

Yes!

**Comment by sbailey** [comment]
`min_altitude: 30 deg` is fine (though I hope that the vast majority of our observations are nowhere near that low...)

Good to know about US/Arizona as a timezone.

**Comment by dkirkby** [comment]
> Good to know about US/Arizona as a timezone.

pytz.timezone('US/Arizona') works, so that's official enough.

> I hope that the vast majority of our observations are nowhere near that low...

The original code never tested `max_airmass` and sometimes scheduled tiles even closer to the horizon.  That needs to be fixed.

> we may want to track the full depth region as a separate list of tiles...

Its a trade off between easy to understand vs precise & reproducible.  That sounds like a new issue to me.

**Comment by dkirkby** [comment]
Any opinions on where output files should go?  We currently generate two FITS files per night, so we don't want them going into the package directory and the $PWD is not a great default.  How about requiring that $DESISURVEY is set and write them there?

**Comment by sbailey** [comment]
+1 for $DESISURVEY, as long as there is also a command line and API function option to bypass that.

**Comment by dkirkby** [comment]
I just added a config method to change the output path after the config has been initialized from the YAML file.  TODO: use this method in `surveysim` to allow the path to be changed via command line.

**Comment by sbailey** [comment]
What is the benefit of wrapping the config file in Configuration and Node classes, vs. just directly reading in the nested dictionary from the yaml file and working with that?  specsim uses a similar Configuration/Node wrapper, and as a non-expert user I found that confusing for mapping what is in the config file to what is actually in memory and what can and cannot be changed.  e.g. why does changing the output path require a special case function to be added to the Configuration object instead of just changing `config['output_path'] = '/path/to/my/output/'`?

I think this is the first place where pytz becomes a new dependency.  That may be ok and well motivated, but it should be explicit in the PR and discussion.  e.g. do we really need full timezone support in the config file or do we just define that all datestamps are in UTC, and that the "night" = YEARMMDD grouping roles over at noon local time in Arizona = 19:00 UTC and we're done?

**Comment by dkirkby** [comment]
> What is the benefit of wrapping the config file in Configuration and Node classes

Its partly for more convenient notation (e.g. `config.programs.DARK.max_sun_altitude()` vs `config['programs']['DARK']['max_sun_altitude']`) but it also provides hooks for implementing validation and conversions.  For example,
```
config['programs']['DARK']['max_sun_altitude'] = '-15 deg'
```
but
```
config.programs.DARK.max_sun_altitude() = -15. * u.deg
```

> specsim uses a similar Configuration/Node wrapper, and as a non-expert user I found that confusing

I learned from that, and kept it much simpler here (the specsim config is inherently more complex since it reads lots of files and needs to interpolate arrays to the internal simulation wavelength grid).
All `desisurvey` config lives within the Configuration object and is accessed directly from it.

> why does changing the output path require a special case function

Because the value in the config file is interpolated using `os.environ` to create a path, and we want to produce a helpful error message if the resulting path does not exist.  The only use case for calling `set_output_path()` is the feature you requested -- being able to change the config default via code.

> I think this is the first place where pytz becomes a new dependency.

I could be convinced to replace `timezone = 'US/Arizona'` with `timezone_offset = -7 hour`, which would eliminate the need for `pytz` but then we are relying on the fact that Arizona is a special timezone with no daylight savings, which feels like a kludge.  Also, its not impossible that Arizona might reinstate daylight savings before the end of DESI, and not inconceivable that we might want to reuse desisurvey for a future survey in a different timezone.

> "night" = YEARMMDD grouping roles over at noon local time in Arizona = 19:00 UTC

This policy is now implemented via `desisurvey.utils.local_noon_on_date()` which encapsulates the details of how we defined the local timezone.

**Comment by dkirkby** [comment]
> TODO: use this method in surveysim to allow the path to be changed via command line.

Done in desihub/surveysim#34

**Comment by dkirkby** [comment]
An update on the `pytz` dependency: the package is pure python, required by `matplotlib`, and included in the base conda install.

**Comment by sbailey** [comment]
Thanks for checking on pytz.  We require matplotlib, so since that already brings in pytz then there is no problem using it directly.

**Comment by dkirkby** [comment]
@weaverba137 I already added `pytz` to `requirements.txt` (which also lists standard python modules, which I didn't expect).  Is there anything else necessary to declare the new `pytz` dependency?

**Comment by weaverba137** [comment]
O, wow, that is a very, very strange requirements.txt file.  As an exercise, I'll go through it entirely.

```
# This is fine, though in principle a dependency on astropy should pull in numpy.
numpy
# This is fine.
astropy
# This is a built-in, doesn't belong here.
datetime
# This is a built-in, doesn't belong here.
os
# This is a built-in, doesn't belong here.
shutil
# This is fine (though is the name of the package in PyPI 'ephem' or 'pyephem'?).
ephem
# This is a built-in, doesn't belong here.
time
# This is actually part of setuptools, so the requirement should be setuptools, not pkg_resources.
pkg_resources
# This is a built-in, doesn't belong here.
operator
# This is fine.
pytz
```

So in summary, you could probably get away with:

```
setuptools
astropy
ephem
pytz
```

However, that does not include DESI packages.  For example, does desisurvey not depend on desiutil at all?

Finally, no Travis tests means no really independent way of knowing whether this will work (though we typically use a different method for setting dependencies in the .travis.yml file).

**Comment by dkirkby** [comment]
Thanks @weaverba137 (and it should be `pyephem` not `ephem`).  I will fix it up on this PR branch.

**Pull request merged**
