### PR TITLE
add desiutil mock modules

### LINKED ISSUE #64: readthedocs error
The [auto-generated docs](http://desisurvey.readthedocs.io/en/latest/api.html#desisurvey.config.Node) have some errors like:
```
ImportError: No module named ‘desiutil’
```
I suspect this is a simple RTD/sphinx config issue so I am assigning to our resident expert @weaverba137.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR fixes #64.

### CODE REVIEW

**Comment by dkirkby** [comment]
Thanks for the quick response!  Did you already trigger a RTD build of this branch?  I think only the RTD owner (you in this case) can build a non-default branch.

**Comment by dkirkby** [comment]
At least I don't see an "Admin" tab [here](https://readthedocs.org/projects/desisurvey/) from my RTD login.

**Comment by weaverba137** [comment]
I will trigger a test build as soon as RTD detects the branch.

**Comment by weaverba137** [comment]
You can now review: http://desisurvey.readthedocs.io/en/rtd-fixes/

**Comment by dkirkby** [comment]
Looks great, thanks!

**Pull request merged**
