### PR TITLE
Added flag and option for computing HA assignment.

### PR DESCRIPTION
**Pull request by mlandriau**
Added option to the afternoon planner to compute or re-compute design hour angles.  If the requested end date is earlier than the nominal survey end date, does the computation until that day.

Although the HA assignment computation is not ready, this PR brings in a number of bug corrections outside that part of the code, including a copy of a bug fix to ephemerides.py copied from @dkirkby 's branch, which affected the results of the code when computeHA is _not_ set.

Other changes:
utils.py: modified inLSTwindow to now accept a numpy array as well as a scalar; re-introduced an approximate computation of the zenith angle with just dec and ha as options.
afternoonplan.py and nextobservation.py: reading of the ha fits file now converts LSTs to degrees right away instead of at the next field selector part.

### CODE REVIEW

**Comment by dkirkby** [comment]
> re-introduced an approximate computation of the zenith angle with just dec and ha as options.

Could you use this function instead?

https://github.com/desihub/desisurvey/blob/nexttile/py/desisurvey/utils.py#L371

**Comment by dkirkby** [comment]
The packages (matplotlib, basemap) you added to `requirements.txt` are not required since they are only imported when calling functions in the `plots` module.

**Comment by mlandriau** [comment]
Yes, I can use that function and cos_zenith_angle_to_airmass instead what is in this branch.

Isn't plot.py part of desisurvey?

**Comment by dkirkby** [comment]
> Isn't plot.py part of desisurvey?

Yes, but `import desisurvey.plots` does not import matplotlib or basemap, so these pkgs are not required.

**Comment by mlandriau** [comment]
I see.  I've just removed them from the list.

**Comment by mlandriau** [comment]
@dkirkby , I replaced the approximate zenith angle computation with the one from your branch and (zenith_to_airmass with cos_zenith_to airmass).

**Comment by dkirkby** [comment]
Ok, I will try to merge both branches back into master later today...

**Pull request merged**
