### PR TITLE
Plotting and ephemerides updates

### PR DESCRIPTION
**Pull request by dkirkby**
Updates to ephemerides:
 - add new method `get_program()` that tabulates program during one night at arbitrary times.

Updates to plots:
 - updates `plot_program()` to use `get_program()` and improve labels.
 - add new `plot_observations()` to display `obslist-all.fits`
 - add new `plot_next_field()` to provide next_field_selector diagnostics.

Updates to afternoon plan:
 - general clean up of unused code and imports.
 - I would like to replace the logic for determining the program at each time step with a single call to the new ephem `get_program()` but haven't had time yet.

Unit tests pass so this is ready for review.

### CODE REVIEW

**Comment by sbailey** [comment]
In the long run we probably need `get_program` to be more flexible to make the decision on the fly based on both ephemeris and current conditions like seeing, sky brightness, and transparency.  e.g. we might drop back to the bright program under bad seeing conditions or light cirrus.  Could you add default values for those parameters to the get_program interface even if we don't use them to make decisions yet?  That at least establishes API placeholders.

It can still be useful to call `get_program` for future dates with default conditions for planning, but let's structure its usage by the next field selector to call it on the fly for each new exposure and not pre-plan the night.

**Comment by dkirkby** [comment]
I am thinking of **program** as the default DARK/GRAY/BRIGHT selection for a given time based purely on ephemerides and therefore locked in for the full 5 years on day one.  With this definition, `get_program()` clearly belongs to the `ephemerides` module and only needs an input time to return its answer (i.e., a nice clean API).

What you are describing is the PROGRAM associated with the tile chosen by next field selector, and I agree that this needs a richer API but I wouldn't put that in the `ephemerides` module.

Perhaps we need a different name to distinguish these two uses of "program"?

**Comment by sbailey** [comment]
I think valid uses of the ephemeris-only "program" are:
  * making plots of what kind of observing conditions are likely to be available when
  * updating the LST assignments based upon remaining time available to the survey (though this calculation could have a scale factor for how often ephemeris-only "DARK" would need to fall back to "BRIGHT" or "GRAY" based upon observing conditions)

But not:
  * choosing which type of tile (DARK, GRAY, BRIGHT) to observe right now (i.e. next field selector).

Maybe these function names would help disambiguate them?
  * `get_ephemeris_program(datetime)`
  * `select_obs_program(datetime, conditions)`

**Comment by dkirkby** [comment]
I like the "ephem-program" vs "obs-program" distinction and nomenclature.

However, since `get_program()` is already a method of the `ephemerides.Ephemerides` class an extra `ephemerides` in the name might be redundant here ;-)  In particular, `get_program` is usually called like this:
```
   dark, gray, bright = ephem.get_program(times)
```

**Comment by sbailey** [comment]
OK, `ephem.get_program(times)` is fine if we consistently use the `ephem.` part.  Could you humor me and pick a place where `select_obs_program()` should go and put a placeholder there that for now just wraps `ephem.get_program()` so that we can use that from the next field selector?

Otherwise fine to merge.

**Comment by dkirkby** [comment]
The new `ephem.get_program()` is currently only used in the plot routines `plot_program()` and `plot_next_field()`.   I think it should also be used in `afternoonplan`, but Martin already has extensive changes there in #34 so that can wait.

I think your suggested `select_obs_program()` would belong in `nextobservation` but that implies a change to the current `nextFieldSelector()` logic, which now picks a tile directly rather than first picking a program and then picking a tile from that program.

I will merge this now, so Martin and I don't get too far out of synch, but lets continue the discussion.

**Pull request merged**
